### ISSUE TITLE
PouchDB ^6.4.3 - Database location or iosDatabaseLocation setting is now mandatory in openDatabase call

### ISSUE THREAD

**Issue by CarlosAyala** [pouchdb-community/pouchdb-adapter-cordova-sqlite#87]
Hi.

I have this issue when run this library in Android 

> Database location or iosDatabaseLocation setting is now mandatory in openDatabase call

My code:

`this._DB = new PouchDB('curriculum.db', {
            adapter: 'cordova-sqlite'
        });`

If I change my code for fix this issue to

`
this._DB = new PouchDB('curriculum.db', {
            adapter: 'cordova-sqlite', 
            iosDatabaseLocation: 'Library',
            androidDatabaseImplementation: 2
        });
`
the IDE shows the message "is not assignable to parameter of type 'DatabaseConfiguration'"

**Comment by darshantejani007** [comment]
I have the same problem! I was initially getting #78 referred error and solved it using their solution, which generated this new error!
CouchDB: 6.4.3
Ionic V1
pouchdb-adapter-cordova-sqlite 2.0.3

**Comment by darshantejani007** [comment]
I had the same error. Doing this worked for me.
```
{ 
    adapter: 'cordova-sqlite',
    location: 'default',
    androidDatabaseImplementation: 2
}

**Comment by CarlosAyala** [comment]
Hi @darshantejani007 .

How do you fixed this issue? I used your code with no luck, still showing me the same error:

`{
adapter: string,
location: string,
androidDatabaseImplementation: number
} is not assignable to parameter of type 'DatabaseConfiguration`

**Comment by rolenjace** [comment]
this._DB =( new PouchDB as any)('curriculum.db', { 
    adapter: 'cordova-sqlite',
    location: 'default',
    androidDatabaseImplementation: 2
});

**Comment by coffeymatt** [comment]
I'm hitting this problem also. I've tried updating my config as above:

```
this.caseDb = (new PouchDB as any)(
          'cases.db', 
          {
            name: 'cases.db',
            adapter: 'cordova-sqlite',    
            location: 'default',         
            iosDatabaseLocation: 'default',
            androidDatabaseImplementation: 2,            
            revs_limit: 1, 
            auto_compaction: true
          }
        );
```

Unfortunately, the error then changes to: 

> ERROR Error: Uncaught (in promise): Error: Missing/invalid DB name
>     Error: Missing/invalid DB name
>         at new PouchDB (http://localhost/vendor.js:145165:11)
>         at http://localhost/main.js:1890:33

Anyone got this to work recently? (am using in an Ionic4/Angular/Capacitor context)

**Comment by coffeymatt** [comment]
The method signature above ("this.caseDb = (new PouchDB as any)(..." doesn't work, but this does:

```
this.caseDb = new PouchDB(
          'cases.db', 
          {
            adapter: 'cordova-sqlite',    
            location: 'default',         
            iosDatabaseLocation: 'default',
            androidDatabaseImplementation: 2,            
            revs_limit: 1, 
            auto_compaction: true
          }
        );
```

**But** only compiles in an angular project with custom type definitions. I've submitted a PR to add a type for this project:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36395

In the mean time, I should be able to run with that type manually dropped into my project (the index.d.ts file).
